import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class Game {
    // the long that counts all dem cupcakes
    private long totalCupcakes = 0;

    public static long clickMultiplier = 1; // Multiplier for cupcakes generated per click

    public static long productionMultiplier = 1; // Multiplier for cupcakes generated by buildings

    public long clickerMultiplier = 1; // Multiplier for Clicker building production

    public long grandmaMultiplier = 1; // Multiplier for Grandma building production

    public long farmMultiplier = 1; // Multiplier for Farm building production

    public long factoryMultiplier = 1; // Multiplier for Factory building production

    public long bankMultiplier = 1; // Multiplier for Bank building production

    public long templeMultiplier = 1; // Multiplier for Temple building production

    public long wizardTowerMultiplier = 1; // Multiplier for Wizard-Tower building production

    // arraylist of buldings
    private List<Building> buildings = new ArrayList<>();
    // for input handling
    private volatile boolean waitingForChoice = false;
    // buffer for input
    private StringBuilder inputBuffer = new StringBuilder();
    // for cupcake generation timing
    private long lastGeneration;
    // track if space was pressed (for space+enter to generate cupcake) wadasdsa
    private boolean spacePressedBeforeEnter = false;

    /**
     * Constructs a new {@code Game} and initializes the available building types.
     */
    public Game() {
        // Initialize your building types
        buildings.add(new Building("Clicker", 1)); // Adds 1 per 5s
        buildings.add(new Building("Grandma", 10)); // Adds 10 per 5s
        buildings.add(new Building("Farm", 50)); // Adds 50 per 5s
        buildings.add(new Building("Factory", 500)); // Adds 500 per 5s
        buildings.add(new Building("Bank", 1000)); // Adds 1000 per 5s
        buildings.add(new Building("Temple", 2000)); // Adds 2000 per 5s
        buildings.add(new Building("Wizard-Tower", 5000)); // Adds 5000 per 5s
    }

    /**
     * Runs the main game loop, handling input and generating cupcakes periodically.
     */
    public void run() {
        lastGeneration = System.currentTimeMillis();
        System.out.println("Game started! Cupcakes will be generated every 5 seconds.");
        System.out.println("Press Enter to see upgrade/buy options...");

        // Main game loop
        while (true) {
            // Check for input
            checkInput();

            // Check for generation THIS IS THE GENERATION TIMER (:
            long currentTime = System.currentTimeMillis();
            if (currentTime - lastGeneration >= 5000) {
                generateCupcakes();
                lastGeneration = currentTime;
            }
            // Sleep briefly to avoid busy waiting
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                break;
            }
        }
    }

    /**
     * Reads and processes user input from the console without blocking the game
     * loop.
     * <p>
     * Space followed by Enter adds one cupcake, while Enter alone opens the buy
     * menu or
     * processes the current menu choice.
     */
    private void checkInput() {
        try {
            // read available input without blocking
            while (System.in.available() > 0) {
                int c = System.in.read();
                if (c == ' ') {
                    spacePressedBeforeEnter = true; // Mark that space was pressed
                } else if (c == '\n' || c == '\r') {
                    // Check if space was pressed before this enter
                    if (spacePressedBeforeEnter) {
                        // Space + Enter = generate cupcake
                        totalCupcakes += clickMultiplier;
                        System.out.println("Added " + clickMultiplier + " cupcake(s)! Total: " + totalCupcakes);
                        spacePressedBeforeEnter = false;
                    } else {
                        // Just Enter = open buy menu
                        String line = inputBuffer.toString().trim();
                        inputBuffer.setLength(0);
                        if (!waitingForChoice) {
                            showOptions();
                            waitingForChoice = true;
                        } else {
                            processChoice(line);
                            waitingForChoice = false;
                        }
                    }
                } else {
                    inputBuffer.append((char) c);
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * Generates cupcakes from all buildings and adds them to the player's total.
     * <p>
     * This method is called periodically by the game loop.
     */
    private void generateCupcakes() {
        int cupcakesProducedThisTurn = 0;

        // Sum up production from all building types
        for (Building b : buildings) {
            cupcakesProducedThisTurn += b.getTotalProduction();
        }

        totalCupcakes += cupcakesProducedThisTurn * productionMultiplier; // Apply global production multiplier
        System.out.println("Added " + cupcakesProducedThisTurn + " cupcakes! Total: " + totalCupcakes);
        System.out.println("Press Enter to see upgrade/buy options...");
    }

    /**
     * Displays the current purchase and upgrade options for all available buildings.
     */
    private void showOptions() {
        System.out.println("\n======================================");
        System.out.println("Current Cupcakes: " + totalCupcakes);
        System.out.println("======================================");
        System.out.println("BUY BUILDINGS (1-7) | UPGRADE BUILDINGS (8-14)\n");

        for (int i = 0; i < buildings.size(); i++) {
            Building b = buildings.get(i);
            double buyPrice = b.getPrice();
            double upgradePrice = b.getUpgradeCost();

            System.out.printf("%d. %-20s (%.0f) | U: %-20s (%.0f) [Lv:%d]\n",
                (i + 1),
                "Buy " + b.name,
                buyPrice,
                "Upgrade " + b.name,
                upgradePrice,
                b.getUpgradeLevel());
        }
        System.out.println("\n======================================");
        System.out.println("CLICK UPGRADES (15-16)\n");
        System.out.println("15. Upgrade Click (Cost: " + String.format("%.0f", getClickUpgradeCost()) + ") [Lv:" + clickMultiplier + "]");
        System.out.println("16. Super Click Upgrade (Cost: 500000)");
        System.out.println("\nEnter your choice (1-16):");
    }

    /**
     * Processes the player's menu choice to either buy, upgrade a building, or upgrade click.
     * Choices 1-7 buy buildings, choices 8-14 upgrade buildings, 15-16 upgrade clicks.
     *
     * @param choice the menu selection entered by the player
     */
    private void processChoice(String choice) {
        int choiceNum;
        try {
            choiceNum = Integer.parseInt(choice);
        } catch (NumberFormatException e) {
            System.out.println("Invalid choice. Please enter a number between 1-16.");
            return;
        }

        // Handle Buy commands (1-7)
        if (choiceNum >= 1 && choiceNum <= 7) {
            int index = choiceNum - 1;
            Building building = buildings.get(index);
            double price = building.getPrice();

            if (totalCupcakes < price) {
                System.out.println("Not enough cupcakes! You need " + String.format("%.0f", price) + " but only have " + totalCupcakes + ".");
                return;
            }

            totalCupcakes -= (long) price;
            building.count++;
            System.out.println("✓ Bought a " + building.name + "! Total Cupcakes: " + totalCupcakes);
        }
        // Handle Upgrade commands (8-14)
        else if (choiceNum >= 8 && choiceNum <= 14) {
            int index = choiceNum - 8;
            if (index >= buildings.size()) {
                System.out.println("Invalid choice.");
                return;
            }

            Building building = buildings.get(index);
            double upgradePrice = building.getUpgradeCost();

            if (totalCupcakes < upgradePrice) {
                System.out.println("Not enough cupcakes! You need " + String.format("%.0f", upgradePrice) + " but only have " + totalCupcakes + ".");
                return;
            }

            totalCupcakes -= (long) upgradePrice;
            building.upgrade();
            System.out.println("✓ Upgraded " + building.name + "! Current level: " + building.getUpgradeLevel());
            System.out.println("  Next upgrade will cost: " + String.format("%.0f", building.getUpgradeCost()));
            System.out.println("  Total Cupcakes: " + totalCupcakes);
        }
        // Handle Click Upgrades (15-16)
        else if (choiceNum == 15) {
            double clickUpgradeCost = getClickUpgradeCost();
            if (totalCupcakes < clickUpgradeCost) {
                System.out.println("Not enough cupcakes! You need " + String.format("%.0f", clickUpgradeCost) + " but only have " + totalCupcakes + ".");
                return;
            }

            totalCupcakes -= (long) clickUpgradeCost;
            clickMultiplier++;
            System.out.println("✓ Click power increased!");
            System.out.println("  Each click now generates: " + clickMultiplier + " cupcakes");
            System.out.println("  Next upgrade will cost: " + String.format("%.0f", getClickUpgradeCost()));
            System.out.println("  Total Cupcakes: " + totalCupcakes);
        }
        else if (choiceNum == 16) {
            long superClickCost = 500000;
            if (totalCupcakes < superClickCost) {
                System.out.println("Not enough cupcakes! You need " + superClickCost + " but only have " + totalCupcakes + ".");
                return;
            }

            totalCupcakes -= superClickCost;
            clickMultiplier *= 10;
            System.out.println("✓ Super Click power granted!");
            System.out.println("  Click power multiplied by 10!");
            System.out.println("  Each click now generates: " + clickMultiplier + " cupcakes");
            System.out.println("  Total Cupcakes: " + totalCupcakes);
        }
        else {
            System.out.println("Invalid choice. Please enter a number between 1-16.");
        }
    }

    /**
     * Calculates the cost for the next click upgrade.
     * Cost is 100 * current click multiplier.
     *
     * @return the cost of the next click upgrade
     */
    private double getClickUpgradeCost() {
        return 100 * clickMultiplier;
    }

    // methods to buy the buildings
    /**
     * Buys a Clicker by increasing the Clicker building count.
     */
    public void buyClicker() {
        // increase count
        buildings.get(0).count++;
    }

    /**
     * Buys a Grandma by increasing the Grandma building count.
     */
    public void buyGrandma() {
        // increase count
        buildings.get(1).count++;
    }

    /**
     * Buys a Farm by increasing the Farm building count.
     */
    public void buyFarm() {
        // increase count
        buildings.get(2).count++;
    }

    /**
     * Buys a Factory by increasing the Factory building count.
     */
    public void buyFactory() {
        // increase count
        buildings.get(3).count++;
    }

    /**
     * Buys a Bank by increasing the Bank building count.
     */
    public void buyBank() {
        // increase count
        buildings.get(4).count++;
    }

    /**
     * Buys a Temple by increasing the Temple building count.
     */
    public void buyTemple() {
        // increase count
        buildings.get(5).count++;
    }

    /**
     * Buys a Wizard Tower by increasing the Wizard-Tower building count.
     */
    public void buyWizardTower() {
        // increase count
        buildings.get(6).count++;
    }
}
